name: Terraform CI/CD

on:
  pull_request:
    branches:
      - main           # Auto plan on PRs to main branch
  push:
    branches:
      - main           # Auto apply on merge to main
  workflow_dispatch:   # Manual trigger for destroy
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: destroy
        type: choice
        options:
          - destroy

env:
  TF_DIR: ./day-3 all config
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.TF_DIR }}

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 🔧 Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: 🧪 Terraform Init
        run: terraform init

      - name: 📋 Terraform Plan
        run: terraform plan

      - name: 🚀 Terraform Apply (on push to main)
        if: github.event_name == 'push'
        run: terraform apply -auto-approve

      - name: 💣 Terraform Destroy (manual only)
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'destroy'
        run: terraform destroy -auto-approve
